version: 2

sources:
  - name: raw_data
    schema: gz_raw_data
    tables:
      - identifier: raw_gz_sales
        name: sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship