version: 2

sources:
  - name: raw_data
    schema: gz_raw_data
    tables:
      - identifier: raw_gz_sales
        name: sales
        description: sales of greenweez
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: greenweez product purchase price
        columns:
          - name: products_id
            tests:
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: greenweez orders shipping fees
        columns:
          - name: orders_id
            tests:
              - unique


models:
  - name: int_orders_margin
    description: purchase cost and margin per order
    columns:
      - name: orders_id
        description: primary key identifying unique order
        tests:
          - unique
          - not_null
      - name: margin
        description: margin calculation per order, margin = revenue - purchase_cost
      - name: purchase_cost
        description: purchase_cost per order, purchase_cost = quantity * purchase_price
  - name: int_orders_operational
    description: operational margin per order
    columns:
      - name: orders_id
        description: primary key identifying unique order
        tests:
          - unique
          - not_null
      - name: operational_margin
        description: operational margin calculation per order, Operational_margin = margin + shipping_fee - log_cost - ship_cost
  - name: int_sales_margin
    description: purchase cost and margin per product
    columns:
      - name: margin
        description: margin calculation per product, margin = revenue - purchase_cost
      - name: purchase_cost
        description: purchase_cost per order, purchase_cost = quantity * purchase_price

